// THIS FILE IS AUTOMATICALLY GENERATED IN:
//
//   build-utils/update-file-index.js
//
// YOU SHOULD NEVER UPDATE THIS FILE DIRECTLY

import HelloA from './HelloA.vue'
import HelloB from './HelloB.vue'
import HelloC from './HelloC.vue'
import HelloD from './sub/HelloD.vue'

// Export components individually
export { HelloA, HelloB, HelloC, HelloD }

// What should happen if the user installs the library as a plugin
function install(Vue) {
  Vue.component('HelloA', HelloA)
  Vue.component('HelloB', HelloB)
  Vue.component('HelloC', HelloC)
  Vue.component('HelloD', HelloD)
}

// Export the library as a plugin
export default { install: install }
